---
fixtures:
  symlinks:
    # Lazy way to get the project source code onto each host for
    # building RPMs in acceptance tests.  Within the tests, we'll
    # relocate to a more appropriate directory.
    simp-adapter: "#{source_dir}"
