HOSTS:
  el7:
    roles:
      - server
      - default
    platform:   el-7-x86_64
    hypervisor: vagrant
    box: centos/7

  el6:
    platform:   el-6-x86_64
    hypervisor: vagrant
    box: centos/6

CONFIG:
  rpm_glob: 'simp-adapter-[0-9]*rpm'
  log_level: verbose
  type: aio
  vagrant_memsize: 256
  synced_folder: disabled
# The simp-adapter is hardcoded to require Puppet 5
  puppet_collection: puppet5
